name: Feed alerts

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch: # allow manual run

jobs:
  run-alerts:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeLaGuardo/setup-clojure@v12
        with:
          lein: latest

      - name: Run alerting job
        run: lein run

      - name: Commit and push generated alerts
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: Update alerts - $(date '+%Y-%m-%d %H:%M:%S %Z')"
          file_pattern: "data/ content/"
